### ISSUE TITLE
Runtime Build Error Unity 2019.4 Windows x86 and Windows x86_64

### ISSUE THREAD

**Issue by TolinSimpson** [eastskykang/UnityMeshImporter#1]
@eastskykang 

Installed via package manager using git link. I can see assimp.dll in the Plugins folder of the build.

COMException
Rethrow as AssimpException: Error loading unmanaged library from path: assimp.dll
Assimp.Unmanaged.UnmanagedLibrary+UnmanagedWindowsLibraryImplementation.NativeLoadLibrary (System.String path) (at <d40f2b0ad6814d4c8094142d8473733f>:0)
Assimp.Unmanaged.UnmanagedLibrary+UnmanagedLibraryImplementation.LoadLibrary (System.String path) (at <d40f2b0ad6814d4c8094142d8473733f>:0)
Assimp.Unmanaged.UnmanagedLibrary.LoadLibrary (System.String libPath) (at <d40f2b0ad6814d4c8094142d8473733f>:0)
Assimp.Unmanaged.UnmanagedLibrary.LoadLibrary () (at <d40f2b0ad6814d4c8094142d8473733f>:0)
Assimp.Unmanaged.UnmanagedLibrary.LoadIfNotLoaded () (at <d40f2b0ad6814d4c8094142d8473733f>:0)
Assimp.Unmanaged.AssimpLibrary.CreatePropertyStore () (at <d40f2b0ad6814d4c8094142d8473733f>:0)
Assimp.AssimpContext.CreateConfigs () (at <d40f2b0ad6814d4c8094142d8473733f>:0)
Assimp.AssimpContext.PrepareImport () (at <d40f2b0ad6814d4c8094142d8473733f>:0)
Assimp.AssimpContext.ImportFile (System.String file, Assimp.PostProcessSteps postProcessFlags) (at <d40f2b0ad6814d4c8094142d8473733f>:0)

I'm having trouble understanding how the DLL is loaded why not use: https://docs.unity3d.com/Manual/PlatformDependentCompilation.html

**Comment by TolinSimpson** [comment]
Fixed by changing lines 93 and 94 in AssimpUnity.cs to include the folder in the file path. The comment on line 92 is wrong.

`                    native64LibPath = pluginsFolder + "/x86_64";
                    native32LibPath = pluginsFolder + "/x86";`

**Comment by eastskykang** [comment]
Thank you very much for reporting. I don't have Windows machine at the moment so can't really test this for Windows. If this change works, can you make a PR?

**Comment by TolinSimpson** [comment]
Tested and works in Unity 2019.4 LTS I submitted a PR.
