### ISSUE TITLE
Wierd/Wrong import of wavefront (.obj ) files

### ISSUE THREAD

**Issue by scooterboo** [eastskykang/UnityMeshImporter#6]
It seems like quads and other 4+ vortex faces are not supported for .obj's.

Here's what I'm getting:
![image](https://user-images.githubusercontent.com/1877986/98103628-25788280-1e4a-11eb-8c1d-74ee9c593354.png)
With this file:
[knight.zip](https://github.com/eastskykang/UnityMeshImporter/files/5487372/knight.zip)

It works fine after I convert it to triangles only:
![image](https://user-images.githubusercontent.com/1877986/98103911-961f9f00-1e4a-11eb-92f4-91da08c80c5c.png)
But I would like to not have to convert every 3D model I have.
[knight2.zip](https://github.com/eastskykang/UnityMeshImporter/files/5487386/knight2.zip)

Solving this might help solve #5

**Comment by scooterboo** [comment]
My pull request #7 fixes all my issues in my project. I have yet to test it on #5.

**Comment by eastskykang** [comment]
@scooterboo Thank you very much for your PR and I'm so sorry for late response. I will quickly test your PR :D

**Comment by eastskykang** [comment]
I confirmed that it works with both knight1 and knight2 obj files. I'm closing this issue now.

![Screenshot from 2021-01-12 15-48-14](https://user-images.githubusercontent.com/3031724/104329936-cf7d2680-54ed-11eb-9747-f188918add61.png)

![Screenshot from 2021-01-12 15-49-17](https://user-images.githubusercontent.com/3031724/104329945-d146ea00-54ed-11eb-8f4f-9b6bc19efb6e.png)
